### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by RyanRHall** [MrRoboman/inceptiogram#6]
Looks good.

I would suggest re-wording phase 4. We should start styling on day 1 (okay, maybe 2). But all components should be styled to completion. I would rename this "page layout" and only reserve the time necessary to put things exactly where you want them. Otherwise, build in time for styling into every other relevant phase.

**Comment by MrRoboman** [comment]
I removed Phase 4 and added styling to the end of each phase.
